    function [ res ] = TBM( x,y )

    x = uint8(x);
    y = uint8(y);

    x_bin_temp = dec2bin(x,8);
    y_bin_temp = dec2bin(y,8);
    x_bin = zeros(1,8);
    y_bin = zeros(1,8);
    
    for i = 1:8
        x_bin(i) = x_bin_temp(i)-'0';
        y_bin(i) = y_bin_temp(i)-'0';
    end

    pp_0 = zero_extend([...
            (y_bin(8)&x_bin(1)),...
            (y_bin(8)&x_bin(2)),...
            (y_bin(8)&x_bin(3))...
        ],2,11);

    pp_1 = zero_extend([...
            (y_bin(7)&x_bin(1)),...
            (y_bin(7)&x_bin(2)),...
            (y_bin(7)&x_bin(3)),...
            (y_bin(7)&x_bin(4)),...
        ],3,11);

    pp_2 = zero_extend([...
            (y_bin(6)&x_bin(1)),...
            (y_bin(6)&x_bin(2)),...
            (y_bin(6)&x_bin(3)),...
            (y_bin(6)&x_bin(4)),...
            0
        ],4,11);

    pp_3 = zero_extend([...
            (y_bin(5)&x_bin(1)),...
            (y_bin(5)&x_bin(2)),...
            (y_bin(5)&x_bin(3)),...
            (y_bin(5)&x_bin(4)),...
            (y_bin(5)&x_bin(5)),...
            0
        ],5,11);

    pp_4 = zero_extend([...
            (y_bin(4)&x_bin(1)),...
            (y_bin(4)&x_bin(2)),...
            (y_bin(4)&x_bin(3)),...
            (y_bin(4)&x_bin(4)),...
            (y_bin(4)&x_bin(5)),...
            (y_bin(4)&x_bin(6)),...
            (y_bin(4)&x_bin(7))...
        ],6,11);

    pp_5 = zero_extend([...
            (y_bin(3)&x_bin(1)),...
            (y_bin(3)&x_bin(2)),...
            (y_bin(3)&x_bin(3)),...
            (y_bin(3)&x_bin(4)),...
            (y_bin(3)&x_bin(5)),...
            (y_bin(3)&x_bin(6)),...
            (y_bin(3)&x_bin(7)),...
            (y_bin(3)&x_bin(8))...
        ],7,11);

    pp_6 = zero_extend([...
            (y_bin(2)&x_bin(1)),...
            (y_bin(2)&x_bin(2)),...
            (y_bin(2)&x_bin(3)),...
            (y_bin(2)&x_bin(4)),...
            (y_bin(2)&x_bin(5)),...
            (y_bin(2)&x_bin(6)),...
            (y_bin(2)&x_bin(7)),...
            (y_bin(2)&x_bin(8)),...
            0
        ],8,11);


    pp_7 = zero_extend([...
            (y_bin(1)&x_bin(1)),...
            (y_bin(1)&x_bin(2)),...
            (y_bin(1)&x_bin(3)),...
            (y_bin(1)&x_bin(4)),...
            (y_bin(1)&x_bin(5)),...
            (y_bin(1)&x_bin(6)),...
            (y_bin(1)&x_bin(7)),...
            (y_bin(1)&x_bin(8)),...
            (y_bin(6)&x_bin(5)),...
            0
        ],9,11);

    pp_8 =[0,0,0,0,0,0,0,0,1,(y_bin(5)&x_bin(6)),0];

    pp = [pp_0;pp_1;pp_2;pp_3;pp_4;pp_5;pp_6;pp_7;pp_8];
    
    pp_dec = zeros(1,9);
    for i = 1:9
        pp_dec(i) = bi2de(fliplr(pp(i,:)));
    end
    res = bitshift(uint16(sum(pp_dec)),5);    
    
 end